### ISSUE TITLE
CV upload logic

### ISSUE THREAD

**Issue by avnogy** [magshimim-next/cv-next#10]
The upload and checking logic should be in a server api that is called by the server action.
In [this branch](https://github.com/magshimim-next/cv-next/compare/supabase-migration...upload) we already implemented domain checking, but it needs to be extended and checked.

**Comment by Aradon267** [comment]
Pseudo code:
```
If(count all cvs of user > 5)
   fail
If(link failed regex tests)
    fail
//Check if failed on both
upload cv object
upload cv image to storage

redirect to the new cv page
```
