### ISSUE TITLE
UI: Rename the Inactive page to Unactivated

### ISSUE THREAD

**Issue by TheGreenOak** [magshimim-next/cv-next#112]
inactive implies that the user hasn't performed an action in some time and gets the inactive page due to inactivity

to resolve the issue you are required to change the design, the redirects and other things that come to your mind that are related (you could search with Ctrl+F for the word "Inactive")

**Comment by Aradon267** [comment]
Which issue do you think takes precedence: this or #144 ? This suggests renaming while the other suggests removing

**Comment by Aradon267** [comment]
After further discussion, #144 will be selected(/invalid will be removed and the homepage will have a popup with instructions)
