### ISSUE TITLE
UI: Make the upload button a button near the user image

### ISSUE THREAD

**Issue by TheGreenOak** [magshimim-next/cv-next#143]
create a + button and put it near the user image instead of a text button
also remove the upload button from the popup when clicking the user

**Comment by DeepanshuMishraa** [comment]
working on it!

**Comment by Aradon267** [comment]
@TheGreenOak , want to have a go at this?

**Comment by TheGreenOak** [comment]
> @TheGreenOak , want to have a go at this?

Yeah I'll try
