### ISSUE TITLE
UI: reorganize the profile page

### ISSUE THREAD

**Issue by TheGreenOak** [magshimim-next/cv-next#145]
the CVs are the most important part of the page so they should take up much more space
there is probably no need for statistics because they take way too much space (If you can find a neater way to show then the go for it)
there is a lot of white space in the profile page so it should be reorganized in some way to use the space better.

**Comment by Aradon267** [comment]
My plan is this:
1. Give more space to the CVs section
2. Add a "dropdown" for the statistics
3. Leave the upper panel unchanged because more things will be added in the future(social links, etc)

**Comment by Aradon267** [comment]
This is the result I got:
![image](https://github.com/user-attachments/assets/133b1ed6-9b20-48f1-91d0-9fadb42833e8)

These are the stats open
![image](https://github.com/user-attachments/assets/ccd70ae4-52e9-4d2e-9211-ebcfef4f690d)
