### ISSUE TITLE
UI: center navbar items

### ISSUE THREAD

**Issue by Aradon267** [magshimim-next/cv-next#172]
Home and feed feel uncentered(they might be deleted soon tho) and same for the NEXT near the theme button
![Image](https://github.com/user-attachments/assets/bc621ff7-c074-409f-92e5-346169183718)

**Comment by TheGreenOak** [comment]
#141 deals with this so there is no reason to fix this bug

**Comment by Aradon267** [comment]
Does it also solve the issue with the next logo and the theme button?

**Comment by Aradon267** [comment]
#141 does remove the button so I'll just fix the logo and theme bit

**Comment by Aradon267** [comment]
Updated from:
![image](https://github.com/user-attachments/assets/b635aa9b-def6-40f1-88eb-837970735a93)

To this:
![image](https://github.com/user-attachments/assets/60a1cb90-6207-439e-bd0a-930d1cc239d1)
