### ISSUE TITLE
BUG: problems with eslint-plugin-prettier

### ISSUE THREAD

**Issue by lordYorden** [magshimim-next/cv-next#186]
a couple days ago I ran into an issue with committing the pre-commit process kept failing do to a dependency problem. 
I realized the problem was the `eslint-plugin-prettier` dependency.
I ran an auto-fix and it changed it from `dependencies` to `devDependencies` on both `package-lock.json` and `package.json`

I am still not sure if this is the problem, but these are the changes I made locally.

**Comment by TheGreenOak** [comment]
what is here to do? how does it affect anyone?

**Comment by lordYorden** [comment]
There is a dependency problems that cause the pre commit checks to fail

**Comment by YechiamW3** [comment]
Did it solve the issue for you locally?
Sounds weird, but there's no actual reason to have this dependency in `dependencies` rather than `devDependencies` anyway so I think you can PR it. But only if it actually solved the problem :)

**Comment by lordYorden** [comment]
For me it did solve it, so pr then?

**Comment by Aradon267** [comment]
A PR here would be great, it's odd because for me there were no problems with eslint, maybe the changes would show something that I somehow ignored or something
