### ISSUE TITLE
Update all usage of user's ID with new username

### ISSUE THREAD

**Issue by Aradon267** [magshimim-next/cv-next#202]
You can read #190 to get a better idea of why and fallbacks and stuff

**Comment by lordYorden** [comment]
I read all of #190 and I have some questions:

1. Do we change only client-side logic?
2. The fallback that is mentioned uses the UUID from before, is that the case?

**Comment by Aradon267** [comment]
I believe that yes and yes(I think we decided that anything the user sees like the URL will be the username and the username would be resolved to get the UUID)

**Comment by lordYorden** [comment]
@Aradon267 I tried to change the logic to use the username 
but for some reason even though the rest of the logic uses username
the page definition must use profileId still.
![image](https://github.com/user-attachments/assets/60d0d282-d382-4c26-8499-b4ddf37a5c82)

What the user now see
![image](https://github.com/user-attachments/assets/e6e78b9b-6baf-4c2c-ae9a-1b60ab52d9a0)

**Comment by Aradon267** [comment]
Not entirely sure that I understand, what do you mean must use profileid? Maybe it due to te folder's name?

**Comment by lordYorden** [comment]
That's what i thought but i wasn't able to change it.
resulted in an EPERM error

**Comment by lordYorden** [comment]
Yes, it is working great

**Comment by Aradon267** [comment]
From #190
> The main point is to work client-side with the username, we don't care if server-side we also use the id.

So I think this is fine, it's weird how even tho you should get the username from there you still use the ID. Can you print the value you get from the URL just to see that it's the username?

**Comment by lordYorden** [comment]
I will check, I think it still is

**Comment by lordYorden** [comment]
![image](https://github.com/user-attachments/assets/8101ae9b-e392-4146-81c3-a10252179657)
it dose show the username

**Comment by lordYorden** [comment]
we should maybe add a DisplayName field.
when @Aradon267 changed his username it showed in the form URI instead
![image](https://github.com/user-attachments/assets/3d9c9287-cac6-45f0-8733-48a4e938dc69)
I added a decode layer to combat this, but we all agree we need a solution @YechiamW3 what do you think?

**Comment by YechiamW3** [comment]
@lordYorden not that I disagree with display name, but in what relation do you bring it up, as related to the profile page?
Let's start with the fact that we should probably disallow special chars for the username (which would eliminate the case you've brought up). That's true either way.
But yeah we can simply change the full_name field to display_name and use it in display-related events (e.g. comments). We don't need a new field for it, as far as I can tell. We'll simply populate that field on first sign-in with the google-given full_name property, and the user will be able to change it in the profile page.

**Comment by lordYorden** [comment]
@YechiamW3  sounds great, do you want me to do it?
