### ISSUE TITLE
credits div does not contain all team members in mobile

### ISSUE THREAD

**Issue by Omria09** [magshimim-next/cv-next#215]
![image](https://github.com/user-attachments/assets/5f0ab6c1-04cb-4d58-9c18-b170291020fc)
As seen in the image, the div's border does not contain all the team when viewed from mobile.
I changed the color to make it look more visible for edits
![image](https://github.com/user-attachments/assets/83ae5b09-dc72-47e6-b05f-aba3677b5952)

**Comment by Omria09** [comment]
![image](https://github.com/user-attachments/assets/b85a7cd7-0b3d-4390-9d18-cdc01a26186e)
solved

**Comment by Aradon267** [comment]
@Omria09 where is the code for this?
