### ISSUE TITLE
UI: cv item stretches on loading (laptop/small screen)

### ISSUE THREAD

**Issue by lordYorden** [magshimim-next/cv-next#242]
![image](https://github.com/user-attachments/assets/2832b4e3-8ab6-416c-9a45-bbb098c0234c)

**Comment by lordYorden** [comment]
same as in #228

**Comment by Aradon267** [comment]
@lordYorden if it's like #228 isn't this a duplicate?

**Comment by Aradon267** [comment]
For now, I've only handled the stretching beyond a specific size, the other things for #228 need a bit more changes
