### ISSUE TITLE
Supabase migration: Choose REST or Drizzle

### ISSUE THREAD

**Issue by YechiamTK** [magshimim-next/cv-next#31]
Supabase provides multiple ways to access its data.
Our two more favourable options are:
1. Supbase's own REST api
2. Drizzle ORM with a direct connection to the pg database

We need to choose our preferred way.
Task is: pros and cons of each method, and choose the better fit.

**Comment by avnogy** [comment]
we can use supabase-js as a rest client and have an orm like experience without using one, i think this is the best option
