### ISSUE TITLE
Supabase migration: Authentication, Connection and Session management

### ISSUE THREAD

**Issue by YechiamTK** [magshimim-next/cv-next#32]
As part of our supabase migration, we need to rewrite the connection, session management and authentication to the database.

Steps are:
1. Manage connection
   * if the connection solution doesn't provide rate-limiting - implement ourselves (use operationBucket or outside library)
3. Manage session (make sure we have control over session timeout, session revalidation etc)
4. Authentication (should replace FirebaseAuthHelper)

**Comment by Aradon267** [comment]
Closing this as this is finished(CR changes were made in the supabase migration branch)
