### ISSUE TITLE
Supabase migration: Services migration

### ISSUE THREAD

**Issue by YechiamW3** [magshimim-next/cv-next#34]
As part of the Supabase migration we need to rewrite all of the query logic in our services (/api).
The service functions should (at least mostly) remain with the same I/O, while only changing the db-related logic.
This includes:
1. comments.ts
2. cvs.ts
3. users.ts

Relatedly, all of the db object types perhaps should be changed to fit the new model (e.g. if we're using an ORM).

**Comment by avnogy** [comment]
cvs:
getPaginatedCvsByQueryFilter - Retrieves paginated CVs based on a query filter and optionally filters out deleted CVs. used in getPaginatedCvs

_getAllCvsByQueryFilter - Retrieves all CVs from the database based on a given query filter and optionally filters out deleted CVs. used for getCvById and getAllCvsByCategory

getCvById - Retrieves a CV by its ID from the database.

getAllCvsByCategory - Retrieves all CVs by a specific category, with an option to filter out deleted CVs. - not used yet

getAllCvsByUserId - Retrieves all CVs by user ID, with an option to filter out deleted CVs. - not used

getPaginatedCvs - Retrieves paginated CVs from the database, with an option to filter out deleted CVs and specify the last ID for pagination. - used in feed

updateCV - Updates a CV in the database and returns a promise that resolves to a DbOperationResult object. is it relevant? - not used

**Comment by YechiamTK** [comment]
> cvs: getPaginatedCvsByQueryFilter - Retrieves paginated CVs based on a query filter and optionally filters out deleted CVs. used in getPaginatedCvs
> 
> _getAllCvsByQueryFilter - Retrieves all CVs from the database based on a given query filter and optionally filters out deleted CVs. used for getCvById and getAllCvsByCategory
> 
> getCvById - Retrieves a CV by its ID from the database.
> 
> getAllCvsByCategory - Retrieves all CVs by a specific category, with an option to filter out deleted CVs. - not used yet
> 
> getAllCvsByUserId - Retrieves all CVs by user ID, with an option to filter out deleted CVs. - not used
> 
> getPaginatedCvs - Retrieves paginated CVs from the database, with an option to filter out deleted CVs and specify the last ID for pagination. - used in feed
> 
> updateCV - Updates a CV in the database and returns a promise that resolves to a DbOperationResult object. is it relevant? - not used

Separate "not used" from "not used yet".
Fetching CVs by User will be used in user page. Updating cv will be used for "resolve".
Can or course be implemented later, but it'll be necessary.

**Comment by avnogy** [comment]
> Separate "not used" from "not used yet". Fetching CVs by User will be used in user page. Updating cv will be used for "resolve". Can or course be implemented later, but it'll be necessary.

of course, the mapping was for knowing what needs to be checked rather than excluding functions from the new implementation.
