### ISSUE TITLE
Review RLS rules for prod

### ISSUE THREAD

**Issue by avnogy** [magshimim-next/cv-next#35]
RLS allows us to control which users are permitted to perform SELECT/INSERT/UPDATE/DELETE statements on specific rows within tables and views.

**Comment by Aradon267** [comment]
# General
## Anon
anon everything using false(except for view of whitelist)

## The rest
`auth.uid() IN (SELECT id FROM whitelisted)`

### When updating general things
```
auth.uid() = user_id
  OR auth.uid() IN (SELECT id FROM admins)
```
user_id from that row(whatever that may be)

# Specifications
## Comments
### Update likes
```
upvotes IS DISTINCT FROM EXCLUDED.upvotes
  AND (EXCLUDED.upvotes IS NOT NULL OR upvotes IS NOT NULL)
```
### Update resolved
If we decide that the uploader of the CV can resolve comments
```
OR auth.uid() IN (
    SELECT uploader_id FROM cvs WHERE cvs.id = comments.cv_id
  )
```
and in general
```
resolved IS DISTINCT FROM EXCLUDED.resolved
  AND (EXCLUDED.resolved IS NOT NULL OR resolved IS NOT NULL)
```

### The rest of the attributes
Only relevant if we want to allow it
```
EXCLUDED.upvotes IS NULL
  AND EXCLUDED.resolved IS NULL
```

## Profiles
### Update type
`auth.uid() IN (SELECT id FROM admin_users)`

The rest of the things(in both profiles and CVS) we don't really care if the user updates(as long as it can only update itself)

**Comment by Aradon267** [comment]
Current setup:
| schemaname | tablename | policyname          | permissive | roles           | cmd    | qual                                                                                                                                                      | with_check                                         |
| ---------- | --------- | ------------------- | ---------- | --------------- | ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| public     | profiles  | insert users        | PERMISSIVE | {authenticated} | INSERT |                                                                                                                                                           | (auth.uid() IN ( SELECT admins.id FROM admins)) |
| public     | profiles  | delete users        | PERMISSIVE | {authenticated} | DELETE | (auth.uid() IN ( SELECT admins.id FROM admins))                                                                                                        |                                                    |
| public     | profiles  | select users        | PERMISSIVE | {authenticated} | SELECT | (auth.uid() IN ( SELECT profiles.id FROM get_whitelisted() get_whitelisted(get_whitelisted)))                                                          |                                                    |
| public     | profiles  | anon - select users | PERMISSIVE | {public}        | SELECT | true                                                                                                                                                      |                                                    |
| public     | profiles  | update users        | PERMISSIVE | {authenticated} | UPDATE | (((auth.uid() IN ( SELECT id.id FROM get_whitelisted() id(id))) AND (auth.uid() = id)) OR (auth.uid() IN ( SELECT id.id FROM get_admins() id(id)))) |                                                    |




| schemaname | tablename | policyname | permissive | roles           | cmd    | qual                                                                                                                                                                                                                                                  | with_check                                                   |
| ---------- | --------- | ---------- | ---------- | --------------- | ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| public     | cvs       | delete cvs | PERMISSIVE | {authenticated} | DELETE | (((auth.uid() IN ( SELECT profiles.id FROM profiles WHERE (profiles.user_type >= 'active'::user_type))) AND (auth.uid() = id)) OR (auth.uid() IN ( SELECT profiles.id FROM profiles WHERE (profiles.user_type = 'admin'::user_type))))      |                                                              |
| public     | cvs       | select cvs | PERMISSIVE | {authenticated} | SELECT | (auth.uid() IN ( SELECT whitelisted.id FROM whitelisted))                                                                                                                                                                                          |                                                              |
| public     | cvs       | update cvs | PERMISSIVE | {authenticated} | UPDATE | (((auth.uid() IN ( SELECT profiles.id FROM profiles WHERE (profiles.user_type >= 'active'::user_type))) AND (auth.uid() = user_id)) OR (auth.uid() IN ( SELECT profiles.id FROM profiles WHERE (profiles.user_type = 'admin'::user_type)))) |                                                              |
| public     | cvs       | insert cvs | PERMISSIVE | {authenticated} | INSERT |                                                                                                                                                                                                                                                       | (auth.uid() IN ( SELECT whitelisted.id FROM whitelisted)) |



| schemaname | tablename | policyname      | permissive | roles           | cmd    | qual                                                                                                                                                           | with_check                                                   |
| ---------- | --------- | --------------- | ---------- | --------------- | ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------ |
| public     | comments  | select comments | PERMISSIVE | {authenticated} | SELECT | (auth.uid() IN ( SELECT whitelisted.id FROM whitelisted))                                                                                                   |                                                              |
| public     | comments  | delete comments | PERMISSIVE | {authenticated} | DELETE | (((auth.uid() IN ( SELECT id.id FROM get_whitelisted() id(id))) AND (auth.uid() = user_id)) OR (auth.uid() IN ( SELECT id.id FROM get_admins() id(id)))) |                                                              |
| public     | comments  | update comments | PERMISSIVE | {authenticated} | UPDATE | (auth.uid() IN ( SELECT whitelisted.id FROM whitelisted))                                                                                                   |                                                              |
| public     | comments  | insert comments | PERMISSIVE | {authenticated} | INSERT |                                                                                                                                                                | (auth.uid() IN ( SELECT whitelisted.id FROM whitelisted)) |
