### ISSUE TITLE
add comments buttons in CV Page

### ISSUE THREAD

**Issue by avnogy** [magshimim-next/cv-next#46]

**Comment by avnogy** [comment]
buttons to add:

- [ ] upvotes/downvotes
- [ ] new comment
- [ ] resolve

**Comment by avnogy** [comment]
comment reply can wait for the ui to be done before, it should use the same logic as in the normal commenting component

**Comment by Aradon267** [comment]
Comment as a reply to another comment with a limit of 1

**Comment by Aradon267** [comment]
I am writing it here so we won't forget
Add icons for likes and confirmation for the delete
