### ISSUE TITLE
split the supabase migration to different prs for cr

### ISSUE THREAD

**Issue by avnogy** [magshimim-next/cv-next#60]
- [ ] map out what is dependent on what and plan out a merge order

**Comment by Aradon267** [comment]
# Features in the branch
## User management
Authentication, authorization

#### Files
middleware.ts
providers\supabase-provider.tsx
hooks\supabaseHooks.ts
app\logout\page.tsx
app\login\page.tsx
app\auth\callback\route.ts

#### Dependencies
General components

#### Uses 
Inactive and landing page

#### What depends on it
User profile component

______
## CVs feed
#### Feature dependencies
CV categories
CvModel and the CV API

### Fetching
#### Files
app\actions\cvs\fetchCvs.ts
app\feed\page.tsx
app\feed\components\CVItem.tsx
app\feed\components\CVItemRSC.tsx
app\feed\components\feed.tsx
providers\cvsProvider.tsx
helpers\imageURLHelper.ts
lib\utils.ts

#### Dependencies
General components, definitions, supabase helper

#### Uses
Filter

#### Related PRs
#61 - updates the source to be supabase and makes it cached

### Filter
#### Files
app\feed\components\filterPanel.tsx
components\ui\filters\\*

#### What uses this
Fetching

 ______
## User profile component
Currently, it only supports login and signout, in the future, it will show user data

#### Files
components\layout\popup.tsx

#### Dependencies
user management

#### What uses it
navbar

____
## General UI
### General components
components\ui\\*
components\theme-provider.tsx

### Navbar
components\layout\navbar.tsx 

#### Uses
User profile component

#### Dependencies
General components

### Landing
app\(landing)\page.tsx
components\pages\hero.tsx
lib\definitions.ts

#### Dependencies
utils, general components

### Inactive
app\inactive\page.tsx
app\inactive\components\inactive.tsx
lib\definitions.ts

#### Dependencies
utils, general components

____
## API and data structures
#### Used
server\api\supabaseHelper.ts
server\api\cvs.ts
types\database.types.ts 
types\models\categories.ts - contains CV categories
app\global.d.ts - contains the CvModel

#### Unused
types\models\userTypes.ts
server\api\users.ts - still Firebase
server\api\utils.ts
server\api\operationBucket.ts
server\api\comments.ts - still Firebase

##### Related PRs
#41 - this PR contains fixed APIs for users and comments as well as actions for these structures

# CR prioritizing
Red means that it MUST use this(the inactive page must use the general components).
Yellow means that it's being used but nothing would happen if we remove it and update some lines(fetch uses filter but we can remove these specific lines and it would be fine).
Green means that there's a branch that's about to update it(changing the source of the fetch)

![Image](https://github.com/magshimim-next/cv-next/assets/86805354/619dd246-60b9-4b66-8d26-f92c22cee8c3)
