### ISSUE TITLE
BUG: Feed page shows for inactive users until first feed page refresh

### ISSUE THREAD

**Issue by YechiamW3** [magshimim-next/cv-next#96]
If an inactive user (or an inexistent user) is "logged in", the user gets redirected to the Feed page.
Even after multiple times of going back and forth from Home to Feed, the user still sees the Feed page.
Only after a few seconds (probably a cache revalidation?) the user gets sent to /inactive when trying to visit Feed again.
See for example this network flow (which shows multiple transitions between Home and Feed, each new visit to Feed generates "fetchCvs"):
![image](https://github.com/user-attachments/assets/e8421398-1590-4b74-b36a-e0283b24951d)

**Comment by Aradon267** [comment]
I tried testing several things like setting no-store and similar headers in middleware responses, removing the suspense in the feed, and doing full refresh after logout but couldn't really figure out a solution

**Comment by Aradon267** [comment]
@YechiamW3 is there a chance that the signout thing + the useUser fixed this? Tried several times but not even a single request to fetchCvs or anything(at least on local)

**Comment by YechiamW3** [comment]
> @YechiamW3 is there a chance that the signout thing + the useUser fixed this? Tried several times but not even a single request to fetchCvs or anything(at least on local)

Interesting, haven't tried it since. I'll try to look into it. But it makes sense that it solved it.

**Comment by YechiamW3** [comment]
> @YechiamW3 have you had the chance to check it out? Or do you need the website to run on the cloud first?

Didn't got to try it yet, but I do think that a trial on cloud deployment will be best. Did we finish providing a stg deployment?

**Comment by Aradon267** [comment]
Forgot to answer, now we did

**Comment by Aradon267** [comment]
I tried testing it several times on the website and it seemed fine so closing for now, if this pops up gain we can try and see this
